#!/usr/bin/env python3
import sys
sys.stdout.reconfigure(encoding='utf-8')
"""
v4 Complete validation suite.
Runs all tests and generates figures.

Usage:
    python run_all_tests.py          # full validation (~14-16 min)
    python run_all_tests.py --quick  # smoke test (~60-70s)
"""

import time


def generate_latex_macros(bg_results, pert_results, cmb_results=None):
    """Write results_macros.tex with key numerical results for the paper."""
    lines = [
        "% Auto-generated by run_all_tests.py -- do not edit manually",
    ]

    def cmd(name, value):
        lines.append(f"\\def\\{name}{{{value}}}")

    # Background
    cmd("aMinBounce", f"{bg_results.get('a_min', 0):.2e}")
    cmd("NpostBounce", f"{bg_results.get('N_post', 0):.1f}")
    cmd("HBounce", f"{bg_results.get('H_bounce', 0):.2e}")
    cmd("gDeviationMax", f"{bg_results.get('g_deviation_max', 0):.1e}")

    # Observables (analytical)
    cmd("nsAnalytical", f"{bg_results.get('n_s', 0):.4f}")
    cmd("rAnalytical", f"{bg_results.get('r', 0):.4f}")
    cmd("AsAnalytical", f"{bg_results.get('A_s', 0):.2e}")

    # Alpha independence
    alpha_res = bg_results.get('alpha_results', {})
    alpha_ok = [a for a in alpha_res if alpha_res[a].get('success')]
    if len(alpha_ok) > 1:
        import numpy as np
        ns_vals = [alpha_res[a]['n_s_numerical'] for a in alpha_ok]
        phi_vals = [alpha_res[a]['phi_CMB'] for a in alpha_ok]
        N_vals = [alpha_res[a].get('N_actual_at_CMB', 0) for a in alpha_ok]
        N_tot_vals = [alpha_res[a].get('N_total_inflation', 0) for a in alpha_ok]
        cmd("nAlphaPoints", f"{len(alpha_ok)}")
        cmd("nsAlphaStd", f"{np.std(ns_vals):.6f}")
        cmd("nsAlphaMean", f"{np.mean(ns_vals):.4f}")
        cmd("phiCMBmeasured", f"{np.mean(phi_vals):.4f}")
        cmd("NactualAtCMB", f"{np.mean(N_vals):.3f}")
        cmd("NtotalInflationAlphaScan", f"{np.mean(N_tot_vals):.2f}")
    else:
        cmd("nAlphaPoints", "0")
        cmd("nsAlphaStd", "N/A")
        cmd("nsAlphaMean", "N/A")
        cmd("phiCMBmeasured", "N/A")
        cmd("NactualAtCMB", "N/A")
        cmd("NtotalInflationAlphaScan", "N/A")

    # Alpha independence -- nontrivial (chi excited)
    nt_res = bg_results.get('alpha_results_nontrivial', {})
    nt_summary = nt_res.get('_summary', {}) if isinstance(nt_res, dict) else {}
    if nt_summary:
        cmd("nAlphaPointsNT", f"{nt_summary.get('n_points', 0)}")
        cmd("nsAlphaMeanNT", f"{nt_summary.get('n_s_mean', 0):.5f}")
        cmd("nsAlphaStdNT", f"{nt_summary.get('n_s_std', 0):.2e}")
        cmd("nsAlphaSpreadNT", f"{nt_summary.get('n_s_spread', 0):.2e}")
        cmd("KchiMaxNT", f"{nt_summary.get('K_chi_max_at_CMB', 0)*100:.1f}")
        cmd("gCMBminNT", f"{nt_summary.get('g_CMB_min', 0):.3f}")
        cmd("gCMBmaxNT", f"{nt_summary.get('g_CMB_max', 0):.3f}")
    else:
        cmd("nAlphaPointsNT", "0")
        cmd("nsAlphaMeanNT", "N/A")
        cmd("nsAlphaStdNT", "N/A")
        cmd("nsAlphaSpreadNT", "N/A")
        cmd("KchiMaxNT", "N/A")
        cmd("gCMBminNT", "N/A")
        cmd("gCMBmaxNT", "N/A")

    # Perturbations
    if pert_results.get('n_s_numerical') is not None:
        cmd("nsNumerical", f"{pert_results['n_s_numerical']:.4f}")
    else:
        cmd("nsNumerical", "N/A")

    cmd("nModesConverged", f"{pert_results.get('n_modes_converged', 0)}")
    cmd("TRSmax", f"{pert_results.get('T_RS_max', 0):.4e}")

    # Constraint accuracy: report worst median for modes up to 5*k_H
    # (deep super-Hubble, where FD comparison is reliable)
    mode_results = pert_results.get('mode_results', {})
    if mode_results:
        import math
        from bounce import V0 as _V0
        _H_inf = math.sqrt(_V0 / 3.0)
        _k_H = float(bg_results.get('a_min', 1.73e5)) * _H_inf
        _k_cut = 5.0 * _k_H
        C_medians = [mode_results[k]['constraint_rel_err']
                     for k in mode_results if k <= _k_cut]
        C_p95s = [mode_results[k]['constraint_p95_err']
                  for k in mode_results if k <= _k_cut]
        if not C_medians:
            C_medians = [mode_results[k]['constraint_rel_err'] for k in mode_results]
            C_p95s = [mode_results[k]['constraint_p95_err'] for k in mode_results]
        cmd("constraintMedian", f"{max(C_medians)*100:.1f}")
        cmd("constraintPninetyfive", f"{max(C_p95s)*100:.1f}")
        # Hamiltonian constraint (independent)
        HC_medians = [mode_results[k].get('hc_rel_err', 0)
                      for k in mode_results if k <= _k_cut]
        if not HC_medians:
            HC_medians = [mode_results[k].get('hc_rel_err', 0) for k in mode_results]
        import math
        hc_worst = max(HC_medians)
        if hc_worst > 0 and hc_worst < 0.01:
            exp = int(math.floor(math.log10(hc_worst * 100)))
            cmd("HCmedian", f"10^{{{exp}}}")
        else:
            cmd("HCmedian", f"{hc_worst*100:.1f}")
    else:
        cmd("constraintMedian", "N/A")
        cmd("constraintPninetyfive", "N/A")
        cmd("HCmedian", "N/A")

    # Fit residuals
    cmd("fitMaxResidual", f"{pert_results.get('max_residual', 0):.3f}")

    # Progressive high-pass fit (bump-tail diagnosis)
    prog = pert_results.get('progressive_fit', {}) or {}
    def _prog_set(x, macro):
        info = prog.get(x, {})
        if info:
            cmd(macro, f"{info['n_s']:.5f}")
            cmd(macro + 'Modes', f"{info['n_modes']}")
            cmd(macro + 'Res', f"{info['max_residual']:.3f}")
        else:
            cmd(macro, "N/A")
            cmd(macro + 'Modes', "0")
            cmd(macro + 'Res', "N/A")
    _prog_set(5.0, 'nsFitKgeqFive')
    _prog_set(10.0, 'nsFitKgeqTen')
    _prog_set(15.0, 'nsFitKgeqFifteen')
    _prog_set(20.0, 'nsFitKgeqTwenty')

    # Gaussian bump parameters
    bf = pert_results.get('bump_fit') or {}
    if bf:
        cmd('bumpAmpLnT', f"{bf['A_lnT2']:.2f}")
        cmd('bumpKpeak', f"{bf['k_peak_over_kH']:.2f}")
        cmd('bumpSigmaLnK', f"{bf['sigma_ln_k']:.2f}")
        cmd('bumpNtotal', f"{bf['N_total_inf']:.0f}")
        # Hidden (pre-CMB) e-folds: from the bounce to CMB-pivot horizon exit.
        # NhiddenEfolds = N_total^sim - N_CMB, the post-bounce stretch that is
        # observationally inaccessible (lies above the CMB pivot).  Used
        # throughout main.tex to replace the previously-hardcoded "~2575".
        cmd('NhiddenEfolds', f"{bf['N_total_inf'] - 60.0:.0f}")
    else:
        cmd('bumpAmpLnT', "N/A")
        cmd('bumpKpeak', "N/A")
        cmd('bumpSigmaLnK', "N/A")
        cmd('bumpNtotal', "N/A")
        cmd('NhiddenEfolds', "N/A")

    # CMB-scale verification
    if cmb_results and cmb_results.get('n_s_cmb') is not None:
        cmd("nsCMBnumerical", f"{cmb_results['n_s_cmb']:.4f}")
        cmd("nsCMBexactFit",
            f"{cmb_results.get('n_s_analytical_exact_fit', 0):.4f}")
        cmd("nsCMBleading",
            f"{cmb_results.get('n_s_analytical_leading', 0):.4f}")
        cmd("nsCMBdelta", f"{cmb_results.get('delta_ns', 0):.2e}")
        cmd("nsCMBdeltaLeading",
            f"{cmb_results.get('delta_ns_leading', 0):.2e}")
        cmd("nCMBmodes", f"{cmb_results.get('n_modes', 0)}")
        cmd("AsRatioMean",
            f"{cmb_results.get('A_s_ratio_mean', 0):.3f}")
        cmd("AsAgreementPct",
            f"{100.0 * cmb_results.get('A_s_agreement', 0):.1f}")
    else:
        cmd("nsCMBnumerical", "N/A")
        cmd("nsCMBexactFit", "N/A")
        cmd("nsCMBleading", "N/A")
        cmd("nsCMBdelta", "N/A")
        cmd("nsCMBdeltaLeading", "N/A")
        cmd("nCMBmodes", "0")
        cmd("AsRatioMean", "N/A")
        cmd("AsAgreementPct", "N/A")

    # Curvature conservation (rigorous |ΔR²/R²| between N=1 and N=5 after exit)
    cc = pert_results.get('curvature_conservation') or {}
    if cc and 'delta' in cc and cc['delta'] == cc['delta']:  # finite check
        cmd("RConservationDelta", f"{cc['delta']:.2e}")
        cmd("RConservationNearly", f"{cc.get('N_early', 1.0):.1f}")
        cmd("RConservationNlate", f"{cc.get('N_late', 5.0):.1f}")
        cmd("RConservationK", f"{cc.get('k', 0):.2f}")
    else:
        cmd("RConservationDelta", "N/A")
        cmd("RConservationNearly", "N/A")
        cmd("RConservationNlate", "N/A")
        cmd("RConservationK", "N/A")

    # Sound speeds c_s² and c_T² through the bounce
    cs = pert_results.get('sound_speeds') or {}
    if cs:
        cs_scalar_ok = "yes" if cs.get('scalar_positive', False) else "no"
        cs_tensor_ok = "yes" if cs.get('tensor_positive', False) else "no"
        cmd("cSSqMaxDev", f"{max(cs['c_phi_sq_max_dev'], cs['c_chi_sq_max_dev']):.0e}")
        cmd("cTSqMaxDev", f"{cs['c_T_sq_max_dev']:.0e}")
        cmd("cSEffDeviation", f"{cs['c_s_eff_deviation']:.2e}")
        cmd("turnRateMax", f"{cs['turn_rate_max']:.2e}")
        cmd("cSPositivity", cs_scalar_ok)
        cmd("cTPositivity", cs_tensor_ok)
        cmd("cSProbeCount", f"{cs.get('n_probe_times', 0)}")
        # c_T_analytical_only flag (from result dict) is not emitted as a
        # LaTeX macro; the corresponding assumption is stated textually in
        # main.tex (sound-speed paragraph + abstract).
        bounce_sample = cs.get('samples', {}).get('bounce', {})
        cmd("HAtBounceSample", f"{bounce_sample.get('H', 0):.1e}")
    else:
        cmd("cSSqMaxDev", "N/A")
        cmd("cTSqMaxDev", "N/A")
        cmd("cSEffDeviation", "N/A")
        cmd("turnRateMax", "N/A")
        cmd("cSPositivity", "N/A")
        cmd("cTPositivity", "N/A")
        cmd("cSProbeCount", "N/A")
        cmd("HAtBounceSample", "N/A")

    # Non-Gaussianity (f_NL via δN formalism)
    fnl = bg_results.get('fNL') or {}
    if fnl:
        cmd("fNLCMBdeltaN", f"{fnl['f_NL_CMB_analytical']:+.4f}")
        cmd("fNLCMBconsistency", f"{fnl['f_NL_CMB_consistency']:+.4f}")
        cmd("fNLCMBconsistencyLeading",
            f"{fnl['f_NL_CMB_consistency_leading']:+.4f}")
        cmd("fNLCMBdelta", f"{fnl['delta_fNL_an_vs_consistency_CMB']:.2e}")
        cmd("fNLCMBdeltaLeading",
            f"{fnl['delta_fNL_an_vs_consistency_CMB_leading']:.2e}")
        cmd("fNLBounce", f"{fnl['f_NL_bounce_analytical']:+.2e}")
        cmd("logTenkCMBoverkH", f"{fnl['log10_kCMB_over_kH']:.0f}")
        cmd("logTenfNLBounceAtCMB", f"{fnl['log10_fNL_bounce_dyn_at_CMB']:.0f}")
        attr = fnl.get('attractor') or {}
        if attr:
            cmd("attractorRelErrMedian", f"{attr['rel_err_median']:.1e}")
            cmd("attractorRelErrMax", f"{attr['rel_err_max']:.1e}")
            cmd("attractorPhiRangeLo", f"{attr['phi_range'][0]:.3f}")
            cmd("attractorPhiRangeHi", f"{attr['phi_range'][1]:.3f}")
        else:
            cmd("attractorRelErrMedian", "N/A")
            cmd("attractorRelErrMax", "N/A")
            cmd("attractorPhiRangeLo", "N/A")
            cmd("attractorPhiRangeHi", "N/A")
    else:
        cmd("fNLCMBdeltaN", "N/A")
        cmd("fNLCMBconsistency", "N/A")
        cmd("fNLCMBconsistencyLeading", "N/A")
        cmd("fNLCMBdelta", "N/A")
        cmd("fNLCMBdeltaLeading", "N/A")
        cmd("fNLBounce", "N/A")
        cmd("logTenkCMBoverkH", "N/A")
        cmd("logTenfNLBounceAtCMB", "N/A")
        cmd("attractorRelErrMedian", "N/A")
        cmd("attractorRelErrMax", "N/A")
        cmd("attractorPhiRangeLo", "N/A")
        cmd("attractorPhiRangeHi", "N/A")

    with open("results_macros.tex", "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("  Generated results_macros.tex")


def main():
    quick = '--quick' in sys.argv

    t0 = time.time()
    mode_label = "QUICK SMOKE TEST" if quick else "COMPLETE VALIDATION"
    print("="*70)
    print(f"BOUNCING COSMOLOGY v4 -- {mode_label}")
    print("="*70)

    # 1. Background + BKL + flatness + alpha independence
    print("\n>>> Running bounce.py validation...")
    from bounce import run_comprehensive_validation
    result = run_comprehensive_validation(quick=quick)
    if result is None:
        print("FATAL: Background validation failed")
        sys.exit(1)
    results, bg = result

    # Check pass count from validation
    n_pass = results.get('n_pass', 0)
    n_total = results.get('n_total', 0)
    n_expected_fail = results.get('n_expected_fail', 0)
    if n_pass + n_expected_fail < n_total:
        print(f"WARNING: {n_total - n_pass - n_expected_fail} unexpected test failures")
        sys.exit(1)

    # 2. Full perturbation analysis
    print("\n>>> Running perturbations.py validation...")
    from perturbations import validate_perturbations_full
    pert_results = validate_perturbations_full(bg, quick=quick)

    # Check perturbation critical results
    pert_failures = []
    if not pert_results.get('constraint_all_ok', False):
        pert_failures.append('momentum constraint')
    if not pert_results.get('curvature_conserved', False):
        pert_failures.append('curvature conservation')
    min_modes = 3 if quick else 6
    if pert_results.get('n_modes_converged', 0) < min_modes:
        pert_failures.append(f"mode convergence ({pert_results.get('n_modes_converged',0)}/{min_modes})")
    if pert_failures:
        print(f"\nFATAL: Perturbation validation failed: {', '.join(pert_failures)}")
        sys.exit(1)

    # 3. CMB-scale inflationary verification
    print("\n>>> Running CMB-scale Starobinsky verification...")
    from perturbations import validate_cmb_inflationary
    cmb_results = validate_cmb_inflationary(quick=quick)
    if cmb_results is not None and cmb_results.get('passed'):
        print(f"  CMB verification PASSED: n_s = {cmb_results['n_s_cmb']:.4f}")
    elif cmb_results is not None and cmb_results.get('n_s_cmb') is not None:
        print(f"  CMB verification: n_s = {cmb_results['n_s_cmb']:.4f} "
              f"(|Delta| = {cmb_results.get('delta_ns', 0):.4f})")
    else:
        print("  CMB verification: insufficient data")

    # 4. Generate LaTeX macros (full mode only — quick mode values are unreliable)
    if quick:
        print("\n>>> Skipping LaTeX macro generation (quick mode)")
    else:
        print("\n>>> Generating LaTeX macros...")
        generate_latex_macros(results, pert_results, cmb_results)

    # 4. Generate figures (full mode only — quick mode skips expensive analyses)
    if quick:
        print("\n>>> Skipping figure generation (quick mode)")
    else:
        print("\n>>> Generating figures...")
        try:
            from generate_figures import generate_all_figures
            generate_all_figures(bg, pert_results)
        except Exception as e:
            print(f"  Figure generation: {e}")
            print("  (Figures can be regenerated with: python generate_figures.py)")

    dt = time.time() - t0
    print(f"\n{'='*70}")
    print(f"COMPLETE in {dt:.1f}s")
    print(f"{'='*70}")


if __name__ == "__main__":
    main()
